// choix par défaut dans les différents écrans à la 1ère connexion
export const userDefault = {
  // étape en cours, page 1  par défaut
  currentPage: 1,
  // page 1  : Type de bien , aucune sélection par défaut
  radioType: -1,
  // page 2  : Etat du bien , aucune sélection par défaut
  radioState: -1,
  // page 3  : Usage du bien , aucune sélection par défaut
  radioUse: -1,
  // page 4  : Situation actuelle , aucune sélection par défaut
  radioSituation: -1,
  // Page 5 : localisation du bien
  country: "FRANCE",
  city: "",
  // Page 6 : Montant du bien
  acquisition: 0,
  works: 0,
  notaryFees: 0,
  // Page 7 : Coordonnées
  mail: "",
  accept: false
};

export const api_Vipoco = "https://vicopo.selfbuild.fr/cherche/";

export const lastPage = 8;

export const tabPageContent = [
  {
    num: 1,
    logoInfo: true, // pour afficher le bouton info
    title: "TYPE DE BIEN",
    radioOption: ["MAISON", "APPARTEMENT"]
  },
  {
    num: 2,
    logoInfo: true,
    title: "ETAT DU BIEN",
    radioOption: ["ANCIEN", "NEUF"]
  },
  {
    num: 3,
    logoInfo: true,
    title: "USAGE DU BIEN",
    radioOption: [
      "Résidence principale",
      "Résidence secondaire",
      "Investissement locatif"
    ]
  },
  {
    num: 4,
    logoInfo: true,
    title: "Votre situation actuelle",
    radioOption: [
      "Locataire",
      "Propriétaire",
      "Bénéficiaire d'un logement de fonction",
      "Hébergé à titre gratuit"
    ]
  },
  {
    num: 5,
    title: "Où se situe le bien à financer ?",
    input: [
      { title: "Dans quel pays se situe votre projet ?*", type: "country" },
      { title: "Ville ou code postal*", type: "city" }
    ],
    description: `La connaissance du code postal du bien permettra de calculer les frais de notaire selon les conditions en vigueur dans le département concerné.
      Si vous êtes en recherche de bien sur plusieurs communes, indiquez une commune ciblée.`
  },
  {
    num: 6,
    title: "DÉFINISSONS LE MONTANT DE VOTRE PROJET",
    input: [
      { title: "Montant estimé de votre acquisition*", type: "number" },
      { title: "Montant estimé des travaux", type: "number" },
      { title: "Frais de notaire*", type: "notaryFees" },
      { title: "Budget total estimé du projet", type: "total" }
    ]
  },
  {
    num: 7,
    title: "Vos coordonnées"
  },
  {
    num: 8,
    title: "Et voilà, le formulaire est terminé !"
  }
];

// liste des pays pour alimenter le Select
export const tabCountry = [
  "Afghanistan",
  "Îles Åland",
  "Albanie",
  "Algérie",
  "Samoa américaines",
  "Andorre",
  "Angola",
  "Anguilla",
  "Antarctique",
  "Antigua-et-Barbuda",
  "Argentine",
  "Arménie",
  "Aruba",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Biélorussie",
  "Belgique",
  "Belize",
  "Bénin",
  "Bermudes",
  "Bhoutan",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Île Bouvet",
  "Brésil",
  "British Virgin Islands",
  "Territoire britannique de l’Océan Indien",
  "Brunei Darussalam",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Iles Cayman",
  "République centrafricaine",
  "Tchad",
  "Chili",
  "Chine",
  "Hong Kong",
  "Macao",
  "Île Christmas",
  "Îles Cocos",
  "Colombie",
  "Comores",
  "République du Congo",
  "République démocratique du Congo",
  "Îles Cook",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatie",
  "Cuba",
  "Chypre",
  "République tchèque",
  "Danemark",
  "Djibouti",
  "Dominique",
  "République dominicaine",
  "Équateur",
  "Égypte",
  "Salvador",
  "Guinée équatoriale",
  "Érythrée",
  "Estonie",
  "Éthiopie",
  "Îles Falkland",
  "Îles Féroé",
  "Fidji",
  "Finlande",
  "France",
  "Guyane française",
  "Polynésie française",
  "Terres australes et antarctiques françaises",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Allemagne",
  "Ghana",
  "Gibraltar",
  "Grèce",
  "Groenland",
  "Grenade",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernesey",
  "Guinée",
  "Guinée-Bissau",
  "Guyane",
  "Haïti",
  "Îles Heard-et-MacDonald",
  "Saint-Siège (Vatican)",
  "Honduras",
  "Hongrie",
  "Islande",
  "Inde",
  "Indonésie",
  "Iran",
  "Irak",
  "Irlande",
  "Ile de Man",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jersey",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Corée du Nord",
  "Corée du Sud",
  "Koweït",
  "Kirghizistan",
  "Laos",
  "Lettonie",
  "Liban",
  "Lesotho",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine",
  "Madagascar",
  "Malawi",
  "Malaisie",
  "Maldives",
  "Mali",
  "Malte",
  "Îles Marshall",
  "Martinique",
  "Mauritanie",
  "Maurice",
  "Mayotte",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Montserrat",
  "Maroc",
  "Mozambique",
  "Myanmar",
  "Namibie",
  "Nauru",
  "Népal",
  "Pays-Bas",
  "Nouvelle-Calédonie",
  "Nouvelle-Zélande",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Île Norfolk",
  "Îles Mariannes du Nord",
  "Norvège",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pérou",
  "Philippines",
  "Pitcairn",
  "Pologne",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Réunion",
  "Roumanie",
  "Russie",
  "Rwanda",
  "Saint-Barthélemy",
  "Sainte-Hélène",
  "Saint-Kitts-et-Nevis",
  "Sainte-Lucie",
  "Saint-Martin (partie française)",
  "Saint-Martin (partie néerlandaise)",
  "Saint-Pierre-et-Miquelon",
  "Saint-Vincent-et-les Grenadines",
  "Samoa",
  "Saint-Marin",
  "Sao Tomé-et-Principe",
  "Arabie Saoudite",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Îles Salomon",
  "Somalie",
  "Afrique du Sud",
  "Géorgie du Sud et les îles Sandwich du Sud",
  "Sud-Soudan",
  "Espagne",
  "Sri Lanka",
  "Soudan",
  "Suriname",
  "Svalbard et Jan Mayen",
  "Eswatini",
  "Suède",
  "Suisse",
  "Syrie",
  "Taiwan",
  "Tadjikistan",
  "Tanzanie",
  "Thaïlande",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turquie",
  "Turkménistan",
  "Îles Turques-et-Caïques",
  "Tuvalu",
  "Ouganda",
  "Ukraine",
  "Émirats Arabes Unis",
  "Royaume-Uni",
  "États-Unis",
  "Îles mineures éloignées des États-Unis",
  "Uruguay",
  "Ouzbékistan",
  "Vanuatu",
  "Venezuela",
  "Viêt Nam",
  "Îles Vierges américaines",
  "Wallis-et-Futuna",
  "Sahara occidental",
  "Yémen",
  "Zambie",
  "Zimbabwe"
];
